### ISSUE TITLE
How to validate array as a body?

### ISSUE THREAD

**Issue by KamilLelonek** [hanami/controller#231]
My example body is:

```json
[
  {
    "id": "2d3037cc-6946-4450-ad4b-fc8630d6f15d",
    "influencer_handle": "influencer258",
    "name": "youtube"
  }
]
```

and my validation is:

```ruby
    params do
      each do
        schema do
          required(:id) { format?(UUID_REGEXP) }
          required(:name).filled(:str?)
          required(:influencer_handle).filled(:str?)
        end
      end
    end
```

However, I get the error like:

```
/Users/squixy/.rvm/gems/ruby-2.4.1/gems/dry-types-0.10.3/lib/dry/types/compiler.rb:80:in `merge': no implicit conversion of Dry::Types::Safe into Hash (TypeError)
	from /Users/squixy/.rvm/gems/ruby-2.4.1/gems/dry-types-0.10.3/lib/dry/types/compiler.rb:80:in `reduce'
	from /Users/squixy/.rvm/gems/ruby-2.4.1/gems/dry-types-0.10.3/lib/dry/types/compiler.rb:80:in `merge_with'
	from /Users/squixy/.rvm/gems/ruby-2.4.1/gems/dry-types-0.10.3/lib/dry/types/compiler.rb:58:in `visit_form_hash'
	from /Users/squixy/.rvm/gems/ruby-2.4.1/gems/dry-types-0.10.3/lib/dry/types/compiler.rb:28:in `visit_type'
	from /Users/squixy/.rvm/gems/ruby-2.4.1/gems/dry-types-0.10.3/lib/dry/types/compiler.rb:15:in `visit'
	from /Users/squixy/.rvm/gems/ruby-2.4.1/gems/dry-types-0.10.3/lib/dry/types/compiler.rb:11:in `call'
	from /Users/squixy/.rvm/gems/ruby-2.4.1/gems/dry-validation-0.10.7/lib/dry/validation/input_processor_compiler.rb:16:in `call'
	from /Users/squixy/.rvm/gems/ruby-2.4.1/gems/dry-validation-0.10.7/lib/dry/validation/schema/deprecated.rb:14:in `input_processor'
	from /Users/squixy/.rvm/gems/ruby-2.4.1/gems/dry-validation-0.10.7/lib/dry/validation/schema/class_interface.rb:165:in `default_options'
	from /Users/squixy/.rvm/gems/ruby-2.4.1/gems/dry-validation-0.10.7/lib/dry/validation/schema/class_interface.rb:35:in `new'
	from /Users/squixy/.rvm/gems/ruby-2.4.1/gems/hanami-validations-1.0.0/lib/hanami/validations.rb:102:in `validations'
	from /Users/squixy/.rvm/gems/ruby-2.4.1/gems/hanami-controller-1.0.0/lib/hanami/action/params.rb:58:in `params'
```

Where exactly is the problem?

**Comment by davydovanton** [comment]
@KamilLelonek could you try this solution?
https://github.com/hanami/validations#array

**Comment by beauby** [comment]
Try replacing `required(:id) { format?(UUID_REGEXP) }` with
```ruby
required(:id).value(format?(UUID_REGEXP))
```

**Comment by jodosha** [comment]
@KamilLelonek Does these suggestions work for you?

**Comment by KamilLelonek** [comment]
I haven't had a chance to try it yet. How to use that with `params`?

**Comment by jodosha** [comment]
@KamilLelonek Thanks for getting back quickly. You put inside the `params` block.

**Comment by KamilLelonek** [comment]
I'm closing this issue as we don't need this anymore so I don't have a chance to check it.
