### ISSUE TITLE
RuntimeError: can't add a new key into hash during iteration

### ISSUE THREAD

**Issue by joelvh** [hanami/controller#290]
Came across this error several times today. I'm not sure if it's due to recent changes on my  end or the amount of requests we're sending to our Hanami app. Is this a logic/threading issue in Hanami or something on my end? My testing hasn't pinpointed the issue yet.

```
RuntimeError at 
================

> can't add a new key into hash during iteration

hanami-controller (1.3.1) lib/hanami/action/glue.rb, line 53
------------------------------------------------------------

   48         # @since 0.3.0
   49         #
   50         # @see Hanami::Action#finish
   51         def finish
   52           super
>  53           @_env[ENV_KEY] = self
   54         end
   55   
   56         # Check if the request's body is a file
   57         #
   58         # @return [TrueClass,FalseClass] the result of the check

App backtrace
-------------



Full backtrace
--------------

 - hanami-controller (1.3.1) lib/hanami/action/glue.rb:53:in `finish'
 - hanami-controller (1.3.1) lib/hanami/action/head.rb:49:in `finish'
 - hanami-controller (1.3.1) lib/hanami/action/callable.rb:87:in `finish'
 - hanami-controller (1.3.1) lib/hanami/action/callable.rb:74:in `call'
 - hanami-router (1.3.1) lib/hanami/routing/endpoint.rb:101:in `call'
 - http_router (0.11.2) lib/http_router.rb:193:in `process_destination_path'
 - (eval):42:in `call'
 - http_router (0.11.2) lib/http_router.rb:288:in `raw_call'
 - hanami-router (1.3.1) lib/hanami/routing/http_router.rb:160:in `raw_call'
 - hanami-router (1.3.1) lib/hanami/router.rb:1019:in `call'
 - newrelic_rpm (5.7.0.350) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
 - rack (2.0.6) lib/rack/builder.rb:153:in `call'
 - rollbar (2.19.2) lib/rollbar/middleware/rack/builder.rb:16:in `block in call_with_rollbar'
 - rollbar (2.19.2) lib/rollbar.rb:146:in `scoped'
 - rollbar (2.19.2) lib/rollbar/middleware/rack/builder.rb:14:in `call_with_rollbar'
 - hanami (1.3.1) lib/hanami/middleware_stack.rb:52:in `call'
 - hanami (1.3.1) lib/hanami/application.rb:169:in `call'
 - /Users/Joel/.rbenv/versions/2.5.1/lib/ruby/2.5.0/delegate.rb:83:in `method_missing'
 - http_router (0.11.2) lib/http_router.rb:193:in `process_destination_path'
 - (eval):18:in `call'
 - http_router (0.11.2) lib/http_router.rb:288:in `raw_call'
 - hanami-router (1.3.1) lib/hanami/routing/http_router.rb:160:in `raw_call'
 - hanami-router (1.3.1) lib/hanami/router.rb:1019:in `call'
 - newrelic_rpm (5.7.0.350) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
 - rack (2.0.6) lib/rack/method_override.rb:22:in `call'
 - newrelic_rpm (5.7.0.350) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
 - hanami (1.3.1) lib/hanami/assets/static.rb:49:in `call'
 - newrelic_rpm (5.7.0.350) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
 - better_errors (2.5.1) lib/better_errors/middleware.rb:84:in `protected_app_call'
 - better_errors (2.5.1) lib/better_errors/middleware.rb:79:in `better_errors_call'
 - better_errors (2.5.1) lib/better_errors/middleware.rb:57:in `call'
 - newrelic_rpm (5.7.0.350) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
 - rollbar (2.19.2) lib/rollbar/middleware/rack.rb:20:in `block in call'
 - rollbar (2.19.2) lib/rollbar.rb:146:in `scoped'
 - rollbar (2.19.2) lib/rollbar/middleware/rack.rb:18:in `call'
 - newrelic_rpm (5.7.0.350) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
 - rack-contrib (2.1.0) lib/rack/contrib/locale.rb:15:in `call'
 - newrelic_rpm (5.7.0.350) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
 - rack (2.0.6) lib/rack/content_length.rb:15:in `call'
 - newrelic_rpm (5.7.0.350) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
 - rack (2.0.6) lib/rack/common_logger.rb:33:in `call'
 - sinatra (2.0.5) lib/sinatra/base.rb:231:in `call'
 - newrelic_rpm (5.7.0.350) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
 - hanami (1.3.1) lib/hanami/app.rb:44:in `call'
 - newrelic_rpm (5.7.0.350) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
 - hanami (1.3.1) lib/hanami/assets/static.rb:49:in `call'
 - rack (2.0.6) lib/rack/lint.rb:49:in `_call'
 - rack (2.0.6) lib/rack/lint.rb:37:in `call'
 - rack (2.0.6) lib/rack/show_exceptions.rb:23:in `call'
 - puma (3.12.0) lib/puma/configuration.rb:225:in `call'
 - puma (3.12.0) lib/puma/server.rb:658:in `handle_request'
 - puma (3.12.0) lib/puma/server.rb:472:in `process_client'
 - puma (3.12.0) lib/puma/server.rb:332:in `block in run'
 - puma (3.12.0) lib/puma/thread_pool.rb:133:in `block in spawn_thread'
```

**Comment by jodosha** [comment]
@joelvh I'm sorry about this problem. Can you please share the action code with us? Thanks.

**Comment by joelvh** [comment]
Hi @jodosha, I've created a GraphQL API endpoint using graphql-ruby. As you can see from the stack trace, I've got some middlewares in there too. I will play with disabling some of those to see if it's one of those.

Would the error be a threading issue, where multiple threads are updating the same object?

Note: As far as I can tell, this is only happening in `development`, not yet noticed the issue on `production`.

Below is generally what the action class looks like. Thanks for your help!

```ruby
# frozen_string_literal: true

module API::Controllers::Endpoints
  class Index
    include API::Action
    accept :json

    before { Timezones.set(current_user&.timezone) }
    after  { Timezones.reset }

    expose :results

    def call(params)
      headers['Access-Control-Allow-Headers'] = 'X-CSRF-Token,Content-Type,Authorize'

      Container['event_store.client'].with_metadata(metadata) do
        @results = schema.execute(
          params[:query],
          variables: parse_variables(params[:variables]),
          context: {
            current_user: current_user&.id,
            auth: authorization_data,
            locale: metadata[:locale]
          },
          operation_name: params[:operationName]
        )
      end
    end

    def parse_variables(variables)
      return variables if variables.is_a?(Hash)
      return parse_variables(variables) if variables.is_a?(String)

      {}
    end

    def authorization_data
      @authorization_data ||= CognitoJWT.from_bearer(
        request.get_header('HTTP_AUTHORIZATION'),
        region: ENV.fetch('COGNITO_REGION'),
        user_pool_id: ENV.fetch('COGNITO_USER_POOL_ID'),
        app_client_id: ENV.fetch('COGNITO_USER_APP_CLIENT_ID')
      ).each_with_object({}) { |(k, v), memo| memo[k.to_sym] = v }
    end

    def current_user
      user_id = authorization_data[:sub]
      @current_user ||= Containerr['repositories.users'].find(user_id) if user_id
    end

    def metadata
      @metadata ||= {
        ip: request.ip,
        locale: request.env['rack.locale'],
        browser: [
          user_agent.name,
          user_agent.full_version,
          user_agent.bot_name
        ].join(';'),
        device: [
          user_agent.device_type,
          user_agent.device_brand,
          user_agent.device_name
        ].join(';'),
        os: [
          user_agent.os_name,
          user_agent.os_full_version
        ].join(';')
      }
    end

    def user_agent
      @user_agent ||= DeviceDetector.new(request.user_agent)
    end

    def schema
      Container['graphql.schema']
    end

    private

    def verify_csrf_token?
      false
    end
  end
end
```

**Comment by joelvh** [comment]
So far, it seems that somehow NewRelic's middleware tracing causes the issue in my application. I also tested NewRelic without `newrelic-hanami` and it still seems to be an issue with the NewRelic agent. Anyone using Hanami v1.3.1 with NewRelic?

Tracked down most of the sources from the stack trace, mostly posting here for my reference:

https://github.com/hanami/controller/blob/v1.3.1/lib/hanami/action/glue.rb#L53
https://github.com/hanami/controller/blob/v1.3.1/lib/hanami/action/head.rb#L49
https://github.com/hanami/controller/blob/v1.3.1/lib/hanami/action/callable.rb#L87
https://github.com/hanami/controller/blob/v1.3.1/lib/hanami/action/callable.rb#L74
https://github.com/hanami/router/blob/v1.3.1/lib/hanami/routing/endpoint.rb#L101
https://github.com/joshbuddy/http_router/blob/v0.11.2/lib/http_router.rb#L193
https://github.com/hanami/router/blob/v1.3.1/lib/hanami/routing/http_router_monkey_patch.rb#L30
https://github.com/joshbuddy/http_router/blob/v0.11.2/lib/http_router.rb#L288
https://github.com/hanami/router/blob/v1.3.1/lib/hanami/routing/http_router.rb#L160
https://github.com/hanami/router/blob/v1.3.1/lib/hanami/router.rb#L1019
https://github.com/newrelic/rpm/blob/master/lib/new_relic/agent/instrumentation/middleware_tracing.rb#L99
https://github.com/rack/rack/blob/2.0.7/lib/rack/builder.rb#L153
https://github.com/rollbar/rollbar-gem/blob/v2.19.2/lib/rollbar/middleware/rack/builder.rb#L16
https://github.com/rollbar/rollbar-gem/blob/v2.19.2/lib/rollbar.rb#L146
https://github.com/rollbar/rollbar-gem/blob/v2.19.2/lib/rollbar/middleware/rack/builder.rb#L14
https://github.com/hanami/hanami/blob/v1.3.1/lib/hanami/middleware_stack.rb#L52
https://github.com/hanami/hanami/blob/v1.3.1/lib/hanami/application.rb#L169

**Comment by jodosha** [comment]
@joelvh Did you had the chance to talk with NewRelic folks about this? Is there anything that we can do here to help?

**Comment by joelvh** [comment]
Hi @jodosha - I have not been  able to find the best place to get a response from them.

**Comment by jodosha** [comment]
@joelvh how about a GH issue in their repo? https://github.com/newrelic/rpm

**Comment by joelvh** [comment]
hi @jodosha I ended up using switching to Sinatra with our GraphQL API. Will revisit Hanami when the revamp with dry-rb is done. Looking forward to that!

**Comment by megatux** [comment]
Happened here with Roda, too. Seems related to Newrelic.
